### ISSUE TITLE
Splash screen not shown in NTR mode

### ISSUE THREAD

**Issue by RocketRobz** [ApacheThunder/NTR_Launcher_Old#1]
When launching NTR Launcher in NTR mode, the splash screen isn't shown, and there's just a black screen at the top, and a white screen at the bottom.

**Comment by ApacheThunder** [comment]
The latest build is not designed to be run in NTR mode anymore. It changes to NTR mode before booting a game. Maybe ahezard's fork of libnds doesn't yet check for DSi mode correctly.

But either way it's not really meant for NTR mode anymore. ;)

**Comment by ApacheThunder** [comment]
By the way if you absolutely must do it this way, you can use original libnds again and run it in NTR mode, but you'll have to restore the volatile's I defined for all the registers (they are commented out now because ahezard's fork of libnds provides them now so I don't have to define them in my code) and rename all the REG_SCFG calls to *SCFG calls. That's really the only part of ahezard's fork of libnds that it uses now. His libnds has built in functions for mode switch and card reset, but they don't appear to work correctly yet (My tests of them just hang the program) so they are not used yet. I still manually define these functions myself the same way as previous builds of NTR Launcher.

I don't quite understand why you are having trouble with it staying in TWL mode. I haven't really looked at NTR Forwarder stuff, but I imagine you just do the forwardering stuff before the mode switch? 

Unlike the alt branch the mode switch happens a bit sooner in the main branch. Look in the launch engine code in the arm7 folder. That's when it's done. So when arm9 calls "runLaunchEngine" in the main function, that's when the mode switch happens. Be sure you adjust the code accordingly so you don't trigger the mode switch too early.

The alt branch doesn't mode switch until the right before the game binary is started. But the main branch mode switches right as the launch engine is started. This is because the launch engine code in the main branch isn't compatible with TWL mode so I mode switch before it's started. But UI and anything you do before launch engine is started is running in TWL mode and will not operate correctly in NTR mode currently due to ahezard's fork of libnds because my UI will immediately break. I restored a missing while loop in the main function as well so looping of arm7 code operates correctly now I believe. Be sure you don't put any of your forwardering code in the while loop. That loop does the error checking for cartridge slot and then launches the launch engine which triggers the launch engine code over on arm7.

**Comment by ApacheThunder** [comment]
Seeing how you managed to get this to work for you in TWL mode I'll close this issue for now. :P
