### ISSUE TITLE
Unfork ntr_launcher from twloader

### ISSUE THREAD

**Issue by bakawun** [ApacheThunder/NTR_Launcher_Old#3]
Dear Apache,

As you are probably aware ntr_launcher was forked into twloader for (what i assume) is its launching of slot1 carts and its flashcard functionality.

I made a diff of the first commit in twloader https://github.com/Robz8/TWLoader/commit/ac7d42c2006e3602e7344e4a13e236a3559319b2 and the probable commit it was based on of ntr_launcher https://github.com/ApacheThunder/NTR_Launcher/commit/1b08c127a1da441ecea9cd5358fd581477edd435
You can view the diff here: https://gist.github.com/bakawun/984b3252258c2feb2b250f166db8ec18

I want to suggest the fork is removed by adding the required functionality to ntr_launcher instead.

The main change appears to be the ability to launch from slot1 without any of the graphical elements used by ntr_launcher, relying instead on the graphics in twloader.

My suggestions are as following:

* Add an option to ntr_launcher to allow twloader to call it in a silent mode without any graphics. I don't know homebrew on the 3ds is capable of doing this but imho this would be ideal.
* Allow ntr_launcher to be compiled in a non-gui mode with a makefile switch.

What are your thoughts on the matter and how could we move forward?

**Comment by ApacheThunder** [comment]
TWLoader could modify the ini file for NTR Launcher and set the bootsplash to not show up. (NTR_Launcher already has this functionality I believe) If Robz8 wanted he could have TWLoader use my build of NTR_Launcher instead. However as I understand it, he uses it for flashcart forwarding as well which are additional features I don't really want to add to my build of NTR Launcher. This is a suggestion better asked of Robz8 on his TWLoader github instead of this. Thanks for the input on this though.
