### ISSUE TITLE
Doesn't preserve history from original code.

### ISSUE THREAD

**Issue by WinterMute** [ApacheThunder/NTR_Launcher_Old#4]
Rather than just starting from some random point it would have been better to fork NitroHax from

https://github.com/chishm/nitrohax

It would be immensely preferable for code to be submitted back and retain the functionality in DS mode rather than making the code less portable.

**Comment by ApacheThunder** [comment]
I started this project before Chishm had his source code on Github. (thus nothing to fork it from).

I do plan on fixing this at some point when I find the time for it.

**Comment by ApacheThunder** [comment]
Ok the main branch has been retired and the alt build no longer requires ahezard's fork of libnds and builds on standard devkitarm r45 and will be updated to work with r46 as soon as I see a push request for it. ( I don't think I'm up to the task of doing this myself. :( )

As for not being forked from NitroHax properly...Not sure how I can correct this without nuking the project and redoing it. This will break forks others have made of NTR Launcher. (mostly forwarders for flashcarts though.... :P ).

Unless I can fix this without destroying the original project links, I have no further plans to correct this.

Maybe I can be convinced to do this at a later point once this is working on latest devkitarm. Will wait and decide then I guess.

**Comment by WinterMute** [comment]
Breaking other forks of this wouldn't be a bad thing.

I lost 4 hours yesterday helping 2 people extricate themselves from the mess caused by following instructions to vandalise the toolchain in order to build this and other projects using inappropriately bodged up build systems and libraries. 4 hours that could have been used doing something productive - like trying to get the IDE code I'm working on to a point where it could be released.

It;'s a major headache and I'd appreciate it if you stopped fragmenting things with no consideration for anyone else. Ahezard's libnds "fork" breaks the ability to build DS applications amongst other things.

**Comment by ApacheThunder** [comment]
Ok so I happened to have nothing to do and was in the mood for tackling this issue. Plus I had the idea of simply "renaming" the old project so I could give other devs time to move over to the new one which for whatever reason the thought didn't come to me at the time I responded to your issue comments. You did post them early morning and I had just woke up, so I was a little cranky. :P

I've properly forked this project from Chishm's NitroHax github. It can be found here:

https://github.com/ApacheThunder/NTR_Launcher

Note that I've renamed this unforked project "NTR_Launcher_Old". I will give the devs of the other forks of my project a little time to move over. I say maybe 7 days is a fair amount of time. (unless they end up doing it sooner. Which ever is faster). At that point this "old" github page of the unforked version will be deleted. The downside is all of the commit history of this project will be lost. I did archive a few older builds in the release page of the new github, but that's the best I could do in that regard. Unless you expected me to commit each old commit one by one...god no I don't have to the time to do that. So I've simply commited the latest version to the new github and called it a day. :P

The only thing left to do at this point is migrate this over to devkitarm r46 and latest libnds/maxmod which I plan to do in the near future hopefully. Oh and the new forked version lacks the old main build entirely. The altbuild will take over as the sole branch for the new forked version as I see no reason to maintain the old branch anymore. (Plus I had not decoupled that branch from Ahezard's libnds. I only did this with the altbuild branch which is now the master branch of the new github repo)

**Comment by WinterMute** [comment]
Not having an issue tracker is pretty bad form.

https://github.com/ApacheThunder/NTR_Launcher/commit/1e2dfed554a62ed883d1b5fc5ea7c2ebabd2ffbe
is wrong. Chishm's source builds and works fine with latest
devkitARM/libnds but the specs & ld file you added are bogus & will
actually cause you major problems.

The two bios source files replicate code that's already in libnds.

The slot reset code (or some variant anyway) should probably be in libnds
rather than being added to NitroHax.

**Comment by ApacheThunder** [comment]
I see. I'm not sure how I can add a issue tracker. it's not available for forks last I checked unless you know of a way of enabling that? I'm not familiar with the finer details of github. If I knew how to add it, I would have done it.

Yeah the specs/ld files will go bye bye once I move this to devkitarm r46. As I understand it correctly sets up the arm7 code/ram entry addresses so I would have no reason to continue using them. You were able to compile NitroHax on latest without having to modify the source/makefile too much? Could you explain what I would need to do?

As for the duplicate bios files I believe shutterbug2000 added those awhile back to make this work in TWL mode. (it would not work otherwise. Maybe he didn't need these? Not sure. If they can be removed and not break anything, then I'll see about doing that.

If there is slot reset code in official libnds I'll use it. I'm just using the code Ahezard made. As it stands right now the code can only really be called once and really only arm7 does it once with some fifo command trickery and what not. Having it setup properly so that arm9 can ask for it anytime would be nice. Would be good to see that in libnds so I don't have to worry about doing that stuff manually. :P

**Comment by ApacheThunder** [comment]
lol so apparently the issue tracker isn't enabled automatically when I fork a project. I always assumed it wasn't possible. I looked at the settings pane for the repo and saw the checkbox for it. Well that's resolved. I enabled it and now it has one.

In no way did I intentionally not have a issue tracker. If I'd known about this sooner, it would have had one from the start. I've hardly ever had to visit that page for any of my repo's so the issue thing being enabled from there was something I wasn't aware of.

I'm not sure why Github enables this by default for new projects but not when a fork is made....

**Comment by bakawun** [comment]
From what I can see here you have roughly 59 commits to this old project of which an unknown number are shared with the 39 commits here https://github.com/ahezard/NitroHax

I don't think cherry picking those would be too bad or time-consuming and you could just merge the project in as a pull request and resolve the conflicts once.

Either way would keep your full history

**Comment by ApacheThunder** [comment]
At this point I'm done making further accommodations for this. I'll settle with how the new fork is setup up. I'm not touching this issue again. I've already got it adjusted to compile and operate with official devkitarm r46 and the associated libnds. However it has introduced issues where the game/cart it attempts to launch hangs or it hangs just before it can launch it. I will focus on correcting this and not so much on cleaning up technicalities like this.

**Comment by WinterMute** [comment]
>lol so apparently the issue tracker isn't enabled automatically when I fork a project. I always assumed it wasn't possible. I looked at the settings pane for the repo and saw the checkbox for it. Well that's resolved. I enabled it and now it has one.

Apologies, I sort of jumped to the conclusion that there was no issue tracker in order to avoid having issues like this posted :p

>I'm not sure why Github enables this by default for new projects but not when a fork is made....

Well, when I'm not jumping to conclusions it does seem like it would be better not to have an issue tracker on a fork that's being used merely to contribute to the canonical upstream.

>However it has introduced issues where the game/cart it attempts to launch hangs or it hangs just before it can launch it. I will focus on correcting this and not so much on cleaning up technicalities like this.

This part is because the DSi needs to be switched back to a DS compatible configuration - i.e. 4meg main RAM and with DS mode bioses paged in before booting.

I noticed a couple of odd things in gbatek that I need to test and some bios reading code that can be replaced with something easier to work with.  In theory it should be easy enough to get it working again in DSi mode but I want to make sure DS mode isn't broken in the process.

**Comment by ApacheThunder** [comment]
Interesting. Well as detailed in the other issue you opened, I found that after testing Nitrohax with only the minimum changes required to make it work on a 3DS, I found that it doesn't get far enough in to actually launch the game. It seems new libnds is causing slot-1 access to break somewhere after the hand over to bootloader/card loading half of the program. The debug boxes NitroHax displayed seemed to indicate a fail on secure area crc or header crc (NTR Launcher had secure area crc check not hault the program so it zipped on past and tried to launch it anyway).

So it appears it's not initing or loading the game binaries correctly or misdetecting something else. With devkitarm r45, the SCFG_EXT/SCFG_ROM triggers I'm using worked perfectly fine in switching things over to NTR spec to allow the game to run. So....Not exacty sure that's the precise issue. Then again I don't know for sure. It doesn't get far enough to even boot the game binaries. Maybe the ram space somehow didn't change correctly but I would have expected this to crash the bootloader section of NTR Launcher/NitroHax instead. Instead that doesn't happen. It's able to show the debug color box stuff and seemingly instead fails to load the cart.

NitroHax does seem to at least see the correct header info during the GUI/cheat selection phase of the program. So card init seems to work correctly at first? It's when the pass over to the bootloader stage is where things break which is where my SCFG changes have to occur. I tested without triggering DSi mode on NTR launcher (can't do this on original NitroHax, some of it's bootloader code doesn't work in TWL mode due to how old it is) and that didn't seem to alter the behavior. Still fails to load things from slot-1.

EDIT: My first guess is maybe differences in how you defined the REG_SCFG registers? That wasn't defined in previous libnds (so I had to define that stuff myself). But libnds now has that, so that's the first thing I would have to see. I'll take a quick look at how they are defined in libnds.

**Comment by tetsuo55** [comment]
@ApacheThunder maybe you can join irc (efnet server channel #3dsdev) and discuss directly with @WinterMute

**Comment by ApacheThunder** [comment]
I'll try, but I've never used IRC before.... :P

**Comment by tetsuo55** [comment]
use this http://chat.efnet.org/
